### ISSUE TITLE
Add support for Atelier Ayesha DX g1n font format

### ISSUE THREAD

**Issue by ZTetriminos** [TekkaGB/P5SFontEditor#1]
So far I've tested the following font files in P5S Font Editor:

- Fatal Frame: Maiden of Black Water (PC)
`Font_SC.g1n` `Font_TC.g1n` `Font_default.g1n`
All the three work.

- Persona 5 Strikers (PC)
`49071c1a.g1n`
Works as intended, and all the mods I tried worked as well.

- Atelier Ayesha DX (PC)
`ArlandDX_font_jp.g1n` `ArlandDX_font_ch.g1n`
Neither of them open. I get a message "Finished parsing g1n!", then, with `ArlandDX_font_ch.g1n`, the app lags until it stops responding. With `ArlandDX_font_jp.g1n`, the app just crashes or, more commonly, freezes completely until I kill it manually in the task manager. In both cases, the app doesn't show any glyph (if it can function at all), I'm pretty sure it's unable to parse them.

As there's no log function, I can't tell what's going on.

If needed, I can provide the files for further testing.

**Comment by TekkaGB** [comment]
Sure, please provide the files and I can look into this further

**Comment by ZTetriminos** [comment]
Thanks!
[Here they are](https://drive.google.com/drive/folders/1ZBHAnd8oil5FxTvsUdEtb21VF1z-ZoKZ?usp=sharing)

**Comment by TekkaGB** [comment]
Turns out, it did actually correctly parse those files. It's just that there were so many glyphs that it lagged out the selection box. I refactored the program to use a search box to account for this issue.
